# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
