# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='文章索引')),
                ('content', models.TextField(verbose_name='评论内容')),
            ],
        ),
    ]
