# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170604_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('login_sequence', models.CharField(max_length=256, verbose_name='登录序列')),
                ('token', models.CharField(max_length=256, verbose_name='token')),
            ],
        ),
    ]
