# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='markdown',
        ),
        migrations.AddField(
            model_name='article',
            name='markdown',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='markdown原始文本'),
            preserve_default=False,
        ),
    ]
